### ISSUE TITLE
Linux: GFX_NO_FRAME +  GFX_OPENGL = freeze at exit

### ISSUE THREAD

**Issue by clebercasali** [freebasic/fbc#122]
Borderless window (GFX_NO_FRAME) will freeze at exit, only in opengl mode (GFX_OPENGL).

[code]
dim as integer fullscreen=0, useopengl=1,  gfxnoswitch=0, borderlesswindow=1, alwaysontop=0, alphaprimitives=0, highpriority=0, multisample=0

dim as long screenflags=iif(fullscreen,&h01,0) or iif(useopengl,&h02,0) or iif(gfxnoswitch,&h04,0) or iif(borderlesswindow,&h08,0) or iif(alwaysontop,&h20,0) or iif(alphaprimitives,&h40,0) or iif(highpriority,&h80,0) or iif(multisample,&h40000,0)	
screenres 1920, 1080, 32, 1, screenflags, 60

do
	screensync
	flip
loop until inkey<>""
[/code]

**Comment by jayrm** [comment]
Looks like hanging on: [gfx_x11.c#L615](https://github.com/freebasic/fbc/blob/91ff1040ae8a16820d79a2f18ba061a3f7216c43/src/gfxlib2/unix/gfx_x11.c#L615)

because stuck on waiting for the frame window to unmap: [gfx_driver_opengl_x11.c#L115](https://github.com/freebasic/fbc/blob/91ff1040ae8a16820d79a2f18ba061a3f7216c43/src/gfxlib2/unix/gfx_driver_opengl_x11.c#L115)

Deadlocks on exit because frame window is never mapped to begin with when graphics mode is created with `fb.GFX_NO_FRAME`.

Should only need a check against `!(fb_x11.flags & DRIVER_NO_FRAME)` to fix.

**Comment by jayrm** [comment]
Fixed in [59af0f0e1b3499b610e8ced424984a80d86cc135]  (fbc-1.08)
Tested on Ubuntu 16.04 x86_64.
