### ISSUE TITLE
How is the "open <file> for input" statement implemented?

### ISSUE THREAD

**Issue by CharlesDDNoble** [freebasic/fbc#129]
Hi FBC Team,

Where should I look to find information about the implementation of FBC Keywords? To be more specific: where can I find information about the C functions used to implement the FBC "**open** *filename* for **Input**" statement. 

From looking at the runtime library, I see various functions that are related to the **input** statement like *fb_InputByte* and *fb_InputInt*. Are these used internally by another function?

**Any information on this would be greatly appreciated!**

*Edit:*
Also, perhaps I should specify why I am interested in this. As part of a research project, I am categorizing test case information for projects contained in a repository for Benchmarking Auto Program Repair systems. See my previous [question](https://github.com/freebasic/fbc/issues/128) for more details. 

I am gathering test case information for *fb_hStr2Double* and a few other related functions and I believe the **input** statement eventually uses them for conversions from Strings to other data types (Double in the case of *fb_hStr2Double*). If my understanding of this is incorrect, please let me know.

**Comment by rversteegen** [comment]
OPEN ... FOR INPUT has nothing to do with fb_InputByte and fb_InputInt. The latter two are part of the implementations of the INPUT and INPUT # statements, which get translated to multiple rtl calls. There are multiple INPUT/WINPUT/LINE INPUT functions and statements. FB has a lot of quirky syntax like this. See the 'See also' section at https://www.freebasic.net/wiki/wikka.php?wakka=KeyPgInput

Because of all the quirks, the surest way to figure out what rtl functions a FB statement/expression translates to is to compile a test program and inspect the generated assembly/C. Nearly all functions in the runtime are called either only from FB code (calls generated from the compiler) which are usually but not always marked with `FBCALL`, or only from other runtime functions.  `fb_hStr2Double` has an 'h' prefix for 'hidden', so that one is definitely called from the runtime only.  I suggest you use gdb to find out the call chain to it.

But if you want to find out *why* a function gets called, you'll want to look at the compiler source. The AST building code makes tangled decisions about which rtl functions to call based on things like syntax and argument types.
A single FB statement is translated to an AST which may contain some calls to runtime functions. The easiest thing to do is use grep to find the relevant code. If you grep for INPUT, you'll find multiple places where INPUT tokens (`FB_TK_INPUT`) can be accepted.  INPUT statements are handled by `cInputStmt` in parser-quirk-file.bas (called from`cQuirkStmt()`), which calls `rtlFileInputGet` to generate the ASTNODE for the rtl call to read a single value from a file (including stdin).
Because there are so many different forms of INPUT, it's easier to go backwards, grepping for `InputByte` instead (do a case-insensitive search and remove the fb_ prefix). In `rtlFileInputGet` you'll find `PROCLOOKUP( INPUTBYTE )` which is the point that a call to this specific rtl function is actually added to the AST. You'll see (both in rtl.bi, which lists the function names, and at the top of rtl-file.bas, which gives the detailed call signature for this function) that the function is called fb_InputByte.

**Comment by rversteegen** [comment]
Oh turns out there is one fb_h function called by the compiler: `fb_hStrDelTemp`, plus also a set of `fb_hPut*`  blend operation functions in the graphics library.

**Comment by CharlesDDNoble** [comment]
@rversteegen Thanks a lot for this information! 

Oh, I see what you are saying about the "open ... for input" statement. That's my fault, I am actually interested in the **input #** statement.

As you suggested, I dug into the .asm file generated using fbc (using the *-R* flag for the compiler) and I now see that **input #** has a call to fb_FileInput and fb_Input* (based on the data type of the *dst* variable). This has saved me so much time!

**Thanks again**
