### ISSUE TITLE
Several suspicious #if _WIN32_WINNT in various winapi headers

### ISSUE THREAD

**Issue by pachuco** [freebasic/fbc#204]
https://github.com/freebasic/fbc/blob/5e93d69f151172694f98f08376838e90f632d6b9/inc/win/shobjidl.bi#L3311

This #ifdef looks both suspiciously placed(only covering single typedef) and having wrong version comparison(if LEQ than NT 5.2).

**Comment by MyTDT-Mysoft** [comment]
ok, theres also several places on winapi .bi files that have 
`#if _WIN32_WINNT = &h0602`
instead of #if _WIN32_WINNT >= `&h0602`

**Comment by jayrm** [comment]
Fixed in fbc-1.10.0 in commit [78e9a44fe6ffcc674bb0ee0a49c872e4000e1921]
Fixed in fbc-1.20.0 in commit [f882d721a421ff3c710b3b0ea46aea91606b005d]

We are still using mingw-w64-v4.0.4 headers for souring the translation of the WinAPI however the generated headers have been refreshed to use later version numbers.
