### ISSUE TITLE
Bi include error in ntdef.bi

### ISSUE THREAD

**Issue by tbbw** [freebasic/fbc#33]
fbc/inc/win/ntdef.bi

#include once "excpt.bi" <- missing bi.
#include once "sdkddkver.bi" <- missing bi.

**Comment by tbbw** [comment]
Uuuh that set off an epic chain reaction of errors to try to fix.
winddk.bi has alot of dupe declarations in it... i do not know where to start on that.

**Comment by dkl** [comment]
For the last Windows API binding update I've generated ntdef.bi using fbfrog ([here](https://github.com/dkl/fbbindings/blob/7ff38d74880d9d637b5f70679d72e4614a3abb7b/makefile#L2925)), not tested though.

**Comment by theonemcdonald** [comment]
I think this is still relevant? I'm seeing the same missing bi files and can't reference ntdef.bi

**Comment by jayrm** [comment]
Fixed in fbc 1.10.0 see commit [6b9323279b45c96fcf78516ab0d7ad82eb59a446] using machine translated (fbfrog) bindings from [freebasic/fbbindings](https://github.com/freebasic/fbc) project
And improved in fbc 1.20.0 commit [f1f8751ac6abc60d5ae5576a253145f00b940292] using a human translated header file (to preserve some header file logic).
