### ISSUE TITLE
feature request : add command line option to specify the toolchain prefix

### ISSUE THREAD

**Issue by stephaneweg** [freebasic/fbc#357]
in linux on window (WSL) i am able to target the raspberry 4, by giving as argument "-arch aarch64 -Wc -march=armv8-a"
by default, it calls gcc, but i use aarch64-none-elf-gcc as cross compiler
now i am forced to create  a symlink from aarch64-none-elf-gcc to gcc  to make the things working

please add a command line option (like "--prefix") so i can tel fbc wich toolchain to use (by example i will use "--prefix aarch64-none-elf-"  and fbc would use it as a prefix for gcc, as, and ld

**Comment by rversteegen** [comment]
It already mostly exists, as `-target`, for example `fbc  -target i686-w64-mingw32.static`. However, unfortunately fbc parses the target (which can take a number of different forms, not just "GNU target triples") and if it doesn't recognise it it throws an error. `aarch64-none-elf` is rejected because it doesn't recognise the OS. So it seems that a `-prefix` argument would be good to have... however... if fbc doesn't know what the target OS and CPU are it can't compile anything anyway. So in this case it might be necessary to to call `fbc -target linux-aarch64 -prefix aarch64-none-elf` or ``fbc -target linux -arch aarch64 -prefix aarch64-none-elf`.

Creating symlinks is not your own option. You can also set the environmental variables `GCC`, `LD`, `AS`, `AR` and more to specify the names of these tools.

**Comment by jayrm** [comment]
fbc already has a `-prefix` option for specifying the path.  I had a similar kind of issue as this, where I wanted to use tools that weren't specifically meant for the target (by tool name) but could nonetheless generate code for other targets.

I added a `-buildprefix` option that will prefix the tool names.
Commit: [14dc9d080335b1f398cd88c593de686352bece5c]
`-buildprefix <name>` will override internal targetprefix option (targetprefix is set by default from `-target` command line option)
(I see that I missed `buildprefix|targetprefix` for standalone fbc in the commit message)

**standalone fbc:**
```
binpath = <prefix>/bin/<target>/
incpath = <prefix>/inc
libpath = <prefix>/lib/<target>
toolname = binpath + <buildprefix|targetprefix> + name.exe
```

**normal fbc:**
```
binpath = <prefix>/freebasic/<targetprefix-|buildprefix>
incpath = prefix/include/freebasic
libpath = prefix/lib[64]/freebasic/target
toolname = binpath + name
```

Additionally, if the tool is not found at the location epxected, the PATH is used and therefore:
`toolname = <targetprefix-|buildprefix> + name`

Internally, this option handling could probably been done a little cleaner, because
in normal fbc the prefix is appended to the bin path, but in standalone, it's added
in when the tool path+name is computed.  Otherwise, externally is probably ok.

**makefile changes**

Along the same lines, I had similar scenario in building fbc itself and made some changes to the `makefile` - mostly by renaming some existing variables and add notes to the top of makefile on usage.
Commit: [64f807a65aac26297b2f87538d606d5a3ddfdc64]

**Comment by jayrm** [comment]
Added in fbc 1.10.0
Commit: [14dc9d080335b1f398cd88c593de686352bece5c]
`-buildprefix <name>` wiki topic: [Compiler Option: -buildprefix](https://www.freebasic.net/wiki/CompilerOptbuildprefix)
