### ISSUE TITLE
File Append Bug

### ISSUE THREAD

**Issue by nsiatras** [freebasic/fbc#393]
I noticed that **Append to file using encoding doesn't work**. I also discussed this on FreeBasic discord and I verified this issue with others.

This doesn't works:
```freebasic
Dim filePath as String = "C:\Users\nsiat\Desktop\Test.txt"
Open filePath For Append encoding "UTF8" As #1
print #1,"TEST"
Close #1
```

This works:
```freebasic
Dim filePath as String = "C:\Users\nsiat\Desktop\Test.txt"
Open filePath For Append  As #1
print #1,"TEST"
Close #1
```

**Comment by jayrm** [comment]
@nsiatras, thank-you for the report.

opening a non-existent file for append always failed because of an incorrect check for not yet written BOM
opening an existing file for append always failed because the file mode didn't support reading the existing BOM

When opening an encoded file (e.g. utf-8) for append:
- if the file doesn't exist yet, it is created and the BOM written
- if the file does exit, the BOM is read and checked

#394 should fix this bug.
