### ISSUE TITLE
can't bootstrap

### ISSUE THREAD

**Issue by throwaway3245** [freebasic/fbc#45]
As I'm sure you're aware, it's not clear how to bootstrap FBC.

Bootstrap of course means to build from source without an existing FBC binary.

It's a common problem.  Consider the solutions SBCL has used over the years.

**Comment by dkl** [comment]
The usual way is to use an existing fbc binary, but there also is a "FreeBASIC-x.xx.x-source-bootstrap" package (see Releases on Github or Files/Source download directory on SourceForge) which contains precompiled compiler sources (.bas precompiled to .asm/.c for various targets) that can be used.

There's some information on this here:
https://www.freebasic.net/wiki/wikka.php?wakka=DevBootstrap

**Comment by dkl** [comment]
The reason for multiple precompiled .c sources is that the C code produced by fbc -gen gcc is target-specific, much like but less than the .asm versions. And for x86 .asm is used instead of .c because .asm is more stable.

**Comment by rversteegen** [comment]
(Oh, I wasn't even aware that asm was used for x86 targets, because I've never compiled a bootstrap target that supported -gen gas)

Right, the C produced is CPU-specific, I misspoke on that. But with CPU fixed, the bootstrapped C code is almost identical for different OSes.

There are two pieces to being able to combine different OS hosts into a single bootstrap-dist build:
1. Whether the files produced by "make bootstrap-dist" can be compiled on multiple hosts. But the compiling and linking is done by "makefile bootstrap", and it's already identical for all targets, and also I can't anything anything target-os (rather than host-os) specific in fbc aside from assembling and linking, showing this is not a problem. (I note that the need for the huge amount of target-specific linking code in fbc is cleanly bypassed by using gcc instead of fbc*)
2. Whether fbc behaves differently on different hosts:
 * AFAICT fbc built for netbsd, openbsd and freebsd hosts all behave identically except for the default target (including the output of -print host) the version string
 * Linux is likewise identical to the BSDs compiled to C (so that FB_TARGETOPT_STACKALIGN16 and FB_TARGETOPT_RETURNINREGS are not used)
 * There is one spot in fbc.bas (hAddDefaultLibs) where __FB_DARWIN__ (and the darwin-specific ENABLE_XQUARTZ define) is used. If this were made a runtime check, then fbc built for darwin hosts should be identical to bsd and linux
 * But DOS, WIN32 and CYGWIN hosts are all different due to path handling, with a bunch of #ifdef's

The makefile could insert the identity of the host OS when doing a bootstrap compile.
So all Unix hosts could easily be combined into a single set of bootstrap C sources per arch since the ABI differences vanish, and DOS/WIN32/CYGWIN too by turning some #ifdef's into runtime checks.
Even if you prefer to provide asm instead of C for bootstrapping, a single generic set of x86 C sources could be provided as an alternative for all OSes for which asm isn't supported or isn't included. Resulting in:
* generic-x86
* generic-x86_64
* generic-arm
* generic-aarch64
* asm-x86-dos
* asm-x86-win32
* asm-x86-linux

*Aside: the build scripts I wrote for my own FB program can use either gcc or fbc to link, defaulting to gcc, as fbc's linking is brittle, not always portable, and quite inflexible. Hmm, maybe we should just add an option to fbc to use gcc for linking, for better portability. We already have to ask a lot of questions of gcc to do the link anyway.

**Comment by dkl** [comment]
Statically linked Linux binaries with musl libc could also be useful for bootstrapping on Linux, by being more portable than the dynamically linked fbcs... but of course that's still an existing fbc binary.

Compiling fbc with another compiler for bootstrapping purposes obviously isn't possible because (as far as I know) there is no other compiler for the language (it's not like it's a standardized BASIC dialect). 

Furthermore, rewriting fbc in a more standard language was never really considered, even though it would solve the bootstrapping problem, because it's a hobby project, and compilers are more fun if they're self-hosting.

**Comment by rversteegen** [comment]
FB is already easy to bootstrap on Linux. OSes which use clang rather than gcc as the system C compiler are more problematic. Supporting clang is another very worthwhile project.

I assume you would be happy to take patches for any of the things I mentioned.

**Comment by dkl** [comment]
To be honest I'm not convinced that it's possible to have "portable" precompiled sources without fixing the fbc C backend code generation to allow it. You're probably right that for some target groups the code is very similar though. For that it could certainly help to try to eliminate #ifdefs from the fbc sources.

But it feels very risky; any change to fbc (adjusting the code generation for one of the targets) would break it. Of course, the makefile could generate all versions, and then diff them to ensure they're equal.
